version: '3.8'

services:
    nginx:
        container_name: nginx
        image: nginx:latest
        ports:
            - 80:80
            - 443:443
        restart: unless-stopped
        volumes:
            - ./livechat:/var/www/html
            - ./proxy/nginx.conf:/etc/nginx/nginx.conf
            - ./proxy/letsencrypt:/etc/letsencrypt
        networks:
            - livechat

    mysql:
        container_name: mysql
        image: mysql:latest
        restart: unless-stopped
        tty: true
        ports:
            - 4306:3306
        environment:
            MYSQL_DATABASE: livechat
            MYSQL_USER: livechat
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - livechat

    laravel:
        container_name: livechat
        build: .
        restart: unless-stopped
        volumes:
            - ./livechat:/var/www/html
        networks:
            - livechat

networks:
    livechat:
        external: true
